name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.44.0
      - name: Install dependencies
        run: pixi install
      - name: Build with pixi
        run: pixi run build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  pypi-publish:
      needs: build
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/wiscopy
      permissions:
        id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
      steps:
        - name: Download all the dists
          uses: actions/download-artifact@v4
          with:
            name: python-package-distributions
            path: dist/
        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
