name: Test Workflow

on:
  pull_request:
    types: [opened, edited, reopened]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.44.0
      - name: Install dependencies
        run: pixi install
      - name: Test with pixi
        run: pixi run -e dev pytest