name: Test Workflow

on:
  [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.4
        with:
          pixi-version: v0.44.0
      - name: Install dependencies
        run: |
          pixi install
      - name: Test with pixi
        run: |
          pixi run -e dev pytest
